### ISSUE TITLE
API for getting instances of a deployed contract instance

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/py-ethpm#13]
### What was wrong?

Packages can contain the addresses of deployed contract instances.  We need an API for retrieving these.

### How can it be fixed?

Since packages can contain deployments across multiple chains we'll need an API that allows us to access these.  I propose the following two APIs

* `Package.deployments`
* `Package.get_deployments(w3)`

The `Package.deployments` API would use the default web3 instance that the `Package` is currently configured with.  If the `Package` has no web3 instance accessing this property should throw an exception indicating that a an instance of web3 is reuired.

The `Package.get_deployments(w3)` allows a user to specify a web3 instance.

Both of these APIs should return a `Deployments` object which exposes a subset of the normal dictionary interface.

* `Deployments.get('MyContract')`
* `Deployments['MyContract']`
* `'MyContract' in Deployments`
* `Deployments.keys()`
* `Deployments.items()`
* `Deployments.values()`

TODO: figure out what to do about validation and what that API looks like.  Does this issue need to stub out any of that functionality.

**Comment by pipermerriam** [comment]
### Part 1 - Definition of done

- [ ] `Package.get_deployments(...)` fails with `ValueError` *if* there is no `w3` instance available
- [ ] `Package.get_deployments(...)` fails with `ValidationError` *if* there is no `deployments` key in package data.
- [ ] `Package.get_deployments(...)` fails with `ValidationError` *if* the `deployments` key in package data is empty.
- [ ] `Package.get_deployments(...)` fails with `ValidationError` *if* there are zero matching blockchain URIs in the `deployments` key.
- [ ] `Package.get_deployments(...)` fails with `ValidationError` *if* there is more than 1 matching blockchain URIs in the `deployments` key.
- [ ] `Package.get_deployments(...)` succeeds returing a `Deployments` instance if none of the above conditions are met.

### Part 2 - definition of done

- [ ] `Deployments.get_contract_instance(contract_name)` fails with `ValidationError` *if* the `contract_name` is not a valid contract name.
- [ ] `Deployments.get_contract_instance(contract_name)` fails with `ValidationError` *if* `contract_name` is not present in the `contract_types` of the package data. (This should be validated **both** during initialization of the `Package` object as well as during the execution of `Deployments.get_contract_instance(...)`.)
- [ ] `Deployments.get_contract_instance(contract_name)` fails with `NotImplementedError` *if* none of the above conditions are met.
